# Generated by Django 3.1.7 on 2021-02-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_auto_20210223_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1024)),
                ('slug', models.SlugField(blank=True, default='', max_length=150, unique=True)),
                ('date_pub', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-date_pub'],
            },
        ),
    ]
